# Directory path for vault
vault_home = "./vault"

# Directory path for daily workspace
workspace_home = "./workspace"

# Directory path for workspace template.
# Files in this dir will be copied when workspace is created.
# NOTE: The filename of submittable file should be 'main.*'.
# (Thus, for example, 'Makefile' will not be recognized as submittable file)
workspace_template = "./template"
