[repository]
# Directory path for vault
vault_home = './vault'

# Directory path for daily workspace
workspace_home = './workspace'

# Directory path for workspace template.
# Files in this dir will be copied each time for a problem workspace is created.
workspace_template = './template'

[expander.cpp]
header_search_dirs = [
  "./include", # Supports relative path (base dir is this config file's dir)
]
expansion_targets = [
  # e.g.) #include <armkn/hoge.hpp>,   #include "armkn/foo/bar.hpp"
  "armkn/**/*.hpp"
]
black_list = [
  "armkn/debug/**/*"
]

[test]
shell = '/bin/sh'
include = '[mM]ain.*'
compile_before_run = true
stdout_capture_max_bytes = 1024
stderr_capture_max_bytes = 4096

[[test.command]]
pattern = '*.cpp'
compile = """\
  g++ \
  #{fileName} \
  -o #{fileStem} \
  -std=c++17 \
  -Wall -Wextra \
"""
run = './#{fileStem}'

[[test.command]]
pattern = '*.pypy.py'
run = 'pypy3 #{fileName}'

[[test.command]]
pattern = '*.py'
run = 'python3 #{fileName}'

[submit]
run_test = true
use_expander = true

# Submission prgramming languages.
# Available lang name can be found by executing
#   `kpr langs atcoder`
[submit.lang]
atcoder = [
  { pattern = '*.cpp', lang = 'C++ (GCC 9.2.1)' },
  { pattern = '*.pypy.py', lang = 'PyPy3 (7.3.0)' },
  { pattern = '*.py', lang = 'Python (3.8.2)' },
]
